spring:
  server:
    port: 8090
    address: 192.168.88.128
  security:
    basic:
      enabled: false
  datasource:

    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
  main:
    allow-circular-references: true
  mvc.pathmatch.matching-strategy: ant_path_matcher
  sql:
    init:
      platform: postgres
