spring:
  security:
    basic:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/argroupcrm
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: false
    #hibernate:
     # ddl-auto: update
  main:
    allow-circular-references: true
  mvc.pathmatch.matching-strategy: ant_path_matcher
  sql:
    init:
      platform: postgres
jwt:
  secret: token
  expiration: 1200000
server:
  port: 8080
  #address: 192.168.88.128